/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.dk9mbs.prohomelog.test.testitems;

import de.dk9mbs.prohomelog.test.AbstractPhlTestItem;

/**
 *
 * @author buehler
 */
public class PhlTestItemFensterSensor extends AbstractPhlTestItem {

    /**
     * Creates new form PhlTestItemThermostatAktor
     */
    public PhlTestItemFensterSensor() {
        initComponents();
    }

    @Override
    public void szenarioTick(int tick) {
        if(de.dk9mbs.prohomelog.test.PropTools.existItem(this.getProp("time_on", ""), String.valueOf(tick) )) {
            this.jCheckBox1.setSelected(true);
            this._publish();
        }

        if(de.dk9mbs.prohomelog.test.PropTools.existItem(this.getProp("time_off", ""), String.valueOf(tick) )) {
            this.jCheckBox1.setSelected(false);
            this._publish();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        labTitle = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jCheckBox1.setText("Fenster zu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        labTitle.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean init() {
        super.init();
        this.labTitle.setText(this.getTitle());
        this._publish();
        return true;
    }
    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        this._publish();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void _publish() {
        String off=this.getProp("item_value_off", "off");
        String on=this.getProp("item_value_on", "on");
        this.jCheckBox1.setText(on);
        String value=off;
        
        if (this.jCheckBox1.isSelected()) value=on;
        this.getPublisher().publish(this.getProp("broker_pub_topic", "dummy/dummy") , value);        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel labTitle;
    // End of variables declaration//GEN-END:variables
}
