/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.dk9mbs.prohomelog.test.testitems;

import de.dk9mbs.prohomelog.test.AbstractPhlTestItem;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author buehler
 */
public class PhlTestItemSliderSensor extends AbstractPhlTestItem {
    private static final Logger logger = Logger.getLogger(PhlTestItemSliderSensor.class.getName());

    /**
     * Creates new form PhlTestItemThermostatAktor
     */
    public PhlTestItemSliderSensor() {
        initComponents();
    }

    @Override
    public void szenarioTick(int tick) {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitle = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        labValue = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        labTitle.setText("jLabel1");

        jSlider1.setMaximum(25);
        jSlider1.setMinimum(-20);
        jSlider1.setValue(10);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        labValue.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labValue))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        this._publish();
    }//GEN-LAST:event_jSlider1StateChanged

    @Override
    public boolean init() {
        super.init();
        this.labTitle.setText(this.getTitle());
        this._publish();
        
        return true;
    }
    
    @Override
    public boolean start() {
        RunTimer timer=new RunTimer(this);
        timer.start();
        
        return true;
    }
    
    private class RunTimer extends java.lang.Thread {
        private PhlTestItemSliderSensor _form;
        
        RunTimer(PhlTestItemSliderSensor form){
            this._form=form;
        }
        
        public void run() {
            try {
                while(true){
                    String value=String.valueOf(this._form.jSlider1.getValue());
                    this._form.getPublisher().publish(this._form.getProp("broker_pub_topic", "dummy/dummy") , value);        
                    java.lang.Thread.sleep(2145);
                }
            } catch(Exception e) {
                logger.log(Level.SEVERE, de.dk9mbs.prohomelog.sys.exception.ExceptionTools.getString(e));
            }
            
        }
    }
    
    private void _publish() {
        String value=String.valueOf(this.jSlider1.getValue());
        this.labValue.setText("Wert:"+value);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labValue;
    // End of variables declaration//GEN-END:variables
}
